### ISSUE TITLE
Missing file of utils.data_augmentation

### ISSUE THREAD

**Issue by yda-cyber** [sangwonim/gca-chiral-morphogenesis#1]
Hi team! Your recent paper is really interesting. I'm trying to reproduce your results and potentially trying new stuff with my own data.

With that being said, after installing this package I found there's might be file missing.
In running: python main.py --config configs/h3.yaml --override "" --log-dir log/h3

1. In the main.py it requires from utils.metrics import MMDCalculator. This file is missing. I was able to found this file from the GCA [reposit.](https://github.com/96lives/gca)
2. In the data.py it requires  from utils import data_augmentation. This file "data_augmentation" I was not able to find anywhere. Is this a missing file or I did anything wrong?

I could not go anyfurther since the data_augmentation is called multiple times. I'm using Minkowski Engine Docker with CUDA 12.1. Please kindly help ;)

@96lives @sangwonim

**Comment by 96lives** [comment]
Sorry for the late reply!

Thanks for the interest in our work.

You wouldn't need any mmd calculations nor the data_augmentation (note that the transform key in the h1 and h3 config is None).
I've just updated the code so that it should train appropriately.

Let me know if you have any troubles :)
